version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend
            - run: npm install
            - run: npm test
  build-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend
            - run: npm install
            - run: npm test
  
workflows:
    build-and-test:
      jobs:
        - build-and-test-backend
        - build-and-test-frontend